name: infin_trulite
description: Infin Trulite - Consolidated Mutual Fund Portfolio Tracker using AMFI live data.
publish_to: "none"
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  sqflite: ^2.2.1
  path: ^1.8.3
  shared_preferences: ^2.2.1
  excel: ^4.0.6
  file_selector: ^1.1.0
  permission_handler: ^11.3.1
  csv: ^5.0.2
  intl: ^0.20.2
  workmanager: ^0.10.7
  fl_chart: ^0.66.2
  translator: ^0.1.7
  url_launcher: ^6.2.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
